name: bro_grow_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  dio: ^5.4.0
  firebase_auth: ^4.15.2
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  fluttertoast: ^8.2.4
  go_router: ^12.1.3
  intl_phone_field: ^3.2.0
  logger: ^2.0.2+1
  pinput: ^3.0.1
  pretty_dio_logger: ^1.3.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  syncfusion_flutter_charts: ^23.2.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
